import React, { useState } from "react";
import {
  StyleSheet,
  Text,
  View,
  ScrollView,
  SafeAreaView,
  TouchableOpacity,
  Image,
  Share,
  Modal,
  Pressable,
  Platform,

} from "react-native";
import { Share2, Save, ArrowLeft, X, Wifi } from "lucide-react-native";
import { useLocalSearchParams, router } from "expo-router";
import { useApp } from "@/providers/AppProvider";

import * as FileSystem from 'expo-file-system';
import * as Sharing from 'expo-sharing';

interface PatternInfo {
  name: string;
  description: string;
  icon: string;
}

const patternDescriptions: Record<string, PatternInfo> = {
  "Concentric Rings of Reflection": {
    name: "Concentric Rings of Reflection",
    description: "Though subtly observed due to lighting and glasses, there appear to be faint concentric circles, which can sometimes playfully indicate layers of life experience and introspection, like rings on a tree.",
    icon: "🌊"
  },
  "Crypts of Deep Thought": {
    name: "Crypts of Deep Thought",
    description: "Small, darker areas within the iris that create depth and character, often associated with contemplative and analytical personalities.",
    icon: "🧠"
  },
  "Radiant Crypts": {
    name: "Radiant Crypts",
    description: "Observe the subtle, intricate openings within your iris, especially around the pupil, which create a captivating radial pattern, unique to your eye's architecture.",
    icon: "✨"
  },
  "Distinct Limbal Ring": {
    name: "Distinct Limbal Ring",
    description: "The dark ring around the outer edge of your iris creates a striking contrast, enhancing the depth and definition of your eye color.",
    icon: "⭕"
  },
  "Nordic Echoes": {
    name: "Nordic Echoes",
    description: "The clear, bright blue of your irises is a charming trait often found predominantly in populations tracing their origins back to Northern Europe.",
    icon: "🌍"
  },
  "Light's Gentle Reminder": {
    name: "Light's Gentle Reminder",
    description: "With less melanin to absorb light, your vibrant blue eyes may be more sensitive to bright sunlight. It's a fun reminder to shield them with stylish sunglasses on sunny days!",
    icon: "☀️"
  }
};

export default function AnalysisScreen() {
  const { isDarkMode } = useApp();
  const { imageUri } = useLocalSearchParams();
  
  // Mock analysis data that matches the screenshot exactly
  const mockAnalysis = {
    dominantColor: {
      name: "Blue-Grey",
      confidence: 90
    },
    colorComposition: [
      { name: "Blue-Grey", hex: "#72A9SF", percentage: 60 },
      { name: "Golden-Brown", hex: "#A8856B", percentage: 20 },
      { name: "Light Grey", hex: "#C8DCEB", percentage: 15 },
      { name: "Dark Blue-Grey", hex: "#485B6B", percentage: 5 }
    ],
    uniquePatterns: ["Unique Patterns Detected"]
  };
  
  const [selectedPattern, setSelectedPattern] = useState<PatternInfo | null>(null);
  const [modalVisible, setModalVisible] = useState(false);


  const handlePatternPress = (patternName: string) => {
    const pattern = patternDescriptions[patternName];
    if (pattern) {
      setSelectedPattern(pattern);
      setModalVisible(true);
    }
  };

  const closeModal = () => {
    setModalVisible(false);
    setSelectedPattern(null);
  };



  const handleShare = async () => {
    try {
      await Share.share({
        message: `Check out my iris analysis! My dominant eye color is ${mockAnalysis.dominantColor.name}.`,
      });
    } catch (error) {
      console.error("Share error:", error);
    }
  };

  const handleSave = async () => {
    try {
      // Create the analysis text content using mock analysis data
      const analysisText = `IRIS ANALYSIS REPORT
${'='.repeat(50)}

Generated on: ${new Date().toLocaleDateString()}

🔍 DOMINANT COLOR:
${mockAnalysis.dominantColor.name} (${mockAnalysis.dominantColor.confidence}% confidence)

🎨 COLOR COMPOSITION:
${mockAnalysis.colorComposition.map(color => `• ${color.name}: ${color.hex} (${color.percentage}%)`).join('\n')}

🔍 UNIQUE PATTERNS DETECTED:
${mockAnalysis.uniquePatterns.map((pattern: string) => `• ${pattern}`).join('\n')}

${'='.repeat(50)}
Disclaimer: This analysis is for entertainment purposes only and is not medical advice.

Generated by Iris Analysis App`;

      if (Platform.OS === 'web') {
        // Web implementation - create and download file
        const blob = new Blob([analysisText], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `iris-analysis-${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        
        console.log('Analysis saved to downloads folder');
      } else {
        // Mobile implementation - use expo-file-system and expo-sharing
        const fileName = `iris-analysis-${new Date().toISOString().split('T')[0]}.txt`;
        const fileUri = FileSystem.documentDirectory + fileName;
        
        await FileSystem.writeAsStringAsync(fileUri, analysisText, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        
        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(fileUri, {
            mimeType: 'text/plain',
            dialogTitle: 'Save Iris Analysis',
          });
        } else {
          console.log(`Analysis saved as ${fileName}`);
        }
      }
    } catch (error) {
      console.error('Save error:', error);
      console.error('Failed to save analysis. Please try again.');
    }
  };

  const handleAnalyzeAnother = () => {
    router.replace("/home");
  };

  return (
    <View style={[styles.container, { backgroundColor: isDarkMode ? '#1a1a3e' : '#f8fafc' }]}>
      <SafeAreaView style={styles.safeArea}>
        <ScrollView 
          style={styles.content}
          showsVerticalScrollIndicator={false}
        >
          {/* Header */}
          <View style={styles.header}>
            <Text style={[styles.headerTitle, { color: isDarkMode ? '#fff' : '#1f2937' }]}>Your Iris Analysis</Text>
            <Text style={[styles.subtitle, { color: isDarkMode ? '#a0a0b8' : '#6b7280' }]}>Here&apos;s what our AI discovered in your eye.</Text>
          </View>

          {/* Iris Image */}
          <View style={[styles.imageCard, { backgroundColor: isDarkMode ? '#2a2a4a' : '#ffffff' }]}>
            <View style={styles.imageContainer}>
              <Image source={{ uri: imageUri as string }} style={styles.irisImage} />
            </View>
            <Text style={[styles.dominantColorName, { color: isDarkMode ? '#fff' : '#1f2937' }]}>{mockAnalysis.dominantColor.name}</Text>
            <Text style={[styles.dominantColorConfidence, { color: isDarkMode ? '#a0a0b8' : '#6b7280' }]}>Dominant Color ({mockAnalysis.dominantColor.confidence}% confidence)</Text>
          </View>

          {/* Horizontal Divider */}
          <View style={[styles.divider, { backgroundColor: isDarkMode ? '#3a3a5a' : '#e5e7eb' }]} />

          {/* Color Composition Section */}
          <View style={[styles.colorCompositionSection, { backgroundColor: isDarkMode ? '#2a2a4a' : '#ffffff' }]}>
            <Text style={[styles.colorCompositionTitle, { color: isDarkMode ? '#fff' : '#1f2937' }]}>Color Composition</Text>
            <View style={styles.colorCompositionList}>
              {mockAnalysis.colorComposition.map((color) => (
                <View key={color.name} style={styles.colorItem}>
                  <View style={[styles.colorSwatch, { backgroundColor: color.hex }]} />
                  <Text style={[styles.colorName, { color: isDarkMode ? '#fff' : '#1f2937' }]}>{color.name}</Text>
                  <Text style={[styles.colorHex, { color: isDarkMode ? '#a0a0b8' : '#6b7280' }]}>{color.hex}</Text>
                  <Text style={[styles.colorPercentage, { color: isDarkMode ? '#fff' : '#1f2937' }]}>{color.percentage}%</Text>
                </View>
              ))}
            </View>
          </View>

          {/* Unique Patterns Section */}
          <TouchableOpacity 
            style={[styles.uniquePatternsSection, { backgroundColor: isDarkMode ? '#2a2a4a' : '#ffffff' }]}
            onPress={() => handlePatternPress("Unique Patterns Detected")}
          >
            <View style={styles.uniquePatternsHeader}>
              <Text style={styles.uniquePatternsIcon}>🔍</Text>
              <Text style={[styles.uniquePatternsTitle, { color: isDarkMode ? '#fff' : '#1f2937' }]}>Unique Patterns Detected</Text>
            </View>
          </TouchableOpacity>



          {/* Action Buttons */}
          <View style={styles.actionButtons}>
            <TouchableOpacity style={[styles.shareButton, { backgroundColor: isDarkMode ? '#2a2a4a' : '#ffffff', borderColor: '#6366f1' }]} onPress={handleShare}>
              <Share2 size={18} color="#6366f1" />
              <Text style={styles.shareButtonText}>Share</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.saveButton} onPress={handleSave}>
              <Save size={18} color="#ffffff" />
              <Text style={styles.saveButtonText}>Save</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.analyzeButton} onPress={handleAnalyzeAnother}>
              <ArrowLeft size={18} color="#ffffff" />
              <Text style={styles.analyzeButtonText}>Analyze Another</Text>
            </TouchableOpacity>
          </View>
        </ScrollView>
      </SafeAreaView>

      {/* Pattern Modal */}
      <Modal
        animationType="slide"
        transparent={true}
        visible={modalVisible}
        onRequestClose={closeModal}
      >
        <View style={styles.modalOverlay}>
          <Pressable style={styles.modalBackdrop} onPress={closeModal} />
          <View style={[styles.modalContent, { backgroundColor: isDarkMode ? '#2a2a4a' : '#ffffff' }]}>
            {/* Iris Image at the top */}
            <View style={styles.modalImageContainer}>
              <View style={styles.modalImageWrapper}>
                <Image source={{ uri: imageUri as string }} style={styles.modalIrisImage} />
                <View style={styles.modalImageOverlay}>
                  <Text style={styles.modalImageCaption}>Your unique iris</Text>
                </View>
              </View>
            </View>
            
            <View style={styles.modalHeader}>
              <View style={styles.modalTitleContainer}>
                <Wifi size={24} color="#10b981" />
                <Text style={[styles.modalTitle, { color: isDarkMode ? '#fff' : '#1f2937' }]}>{selectedPattern?.name || "Unique Patterns Detected"}</Text>
              </View>
              <TouchableOpacity onPress={closeModal} style={styles.modalCloseButton}>
                <X size={24} color={isDarkMode ? '#8a8aa0' : '#6b7280'} />
              </TouchableOpacity>
            </View>
            <Text style={[styles.modalDescription, { color: isDarkMode ? '#a0a0b8' : '#4b5563' }]}>
              {selectedPattern?.description || "Your iris displays unique patterns that make it distinctly yours. These intricate details create a beautiful and individual characteristic that is as unique as a fingerprint."}
            </Text>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  safeArea: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
  },
  header: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#6b7280',
    textAlign: 'center',
  },
  imageCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  imageContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: '#10b981',
    padding: 4,
    marginBottom: 12,
  },
  irisImage: {
    width: '100%',
    height: '100%',
    borderRadius: 56,
  },
  imageCaption: {
    fontSize: 14,
    color: '#6b7280',
  },
  section: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
    marginLeft: 8,
  },
  sectionDescription: {
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 20,
  },
  patternTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
  },
  patternTag: {
    backgroundColor: '#6366f1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  patternTagText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '500',
  },
  clickHere: {
    color: '#6366f1',
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  rarityIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  rarityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    marginBottom: 4,
  },
  rarityLabel: {
    fontSize: 12,
    color: '#6b7280',
  },
  rarityBar: {
    height: 8,
    backgroundColor: '#e5e7eb',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  rarityFill: {
    height: '100%',
    width: '91%',
    backgroundColor: '#ec4899',
    borderRadius: 4,
  },
  rarityPercentage: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ec4899',
    textAlign: 'center',
  },
  metricsContainer: {
    marginTop: 16,
    gap: 12,
  },
  metric: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metricIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  metricLabel: {
    fontSize: 14,
    color: '#6b7280',
    flex: 1,
  },
  metricValue: {
    fontSize: 14,
    color: '#1f2937',
    fontWeight: '500',
  },
  healthSection: {
    marginTop: 8,
    marginBottom: 24,
  },
  healthTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1f2937',
    textAlign: 'center',
    marginBottom: 20,
  },
  healthCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  healthContent: {
    flex: 1,
    marginLeft: 12,
  },
  healthItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 8,
  },
  healthIndicatorCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  healthIndicatorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  healthIndicatorLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  healthIndicatorIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  healthIndicatorEmoji: {
    fontSize: 14,
    color: '#6b7280',
  },
  healthIndicatorInfo: {
    flex: 1,
  },
  healthIndicatorTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 4,
  },
  healthIndicatorChevron: {
    padding: 4,
  },
  healthIndicatorDetails: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  healthIndicatorDescription: {
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 20,
    marginBottom: 16,
  },
  comparisonSection: {
    backgroundColor: '#f9fafb',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#10b981',
  },
  comparisonTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  comparisonText: {
    fontSize: 12,
    color: '#4b5563',
    lineHeight: 16,
    fontStyle: 'italic',
  },
  healthStatus: {
    alignSelf: 'flex-start',
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  healthStatusText: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '500',
  },
  healthDescription: {
    fontSize: 14,
    color: '#4b5563',
    lineHeight: 20,
  },
  disclaimer: {
    fontSize: 12,
    color: '#6366f1',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 40,
  },
  shareButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#6366f1',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 6,
  },
  shareButtonText: {
    color: '#6366f1',
    fontSize: 14,
    fontWeight: '600',
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6366f1',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 6,
  },
  saveButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  analyzeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#6366f1',
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderRadius: 12,
    gap: 6,
    minHeight: 48,
  },
  analyzeButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalBackdrop: {
    flex: 1,
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 10,
  },
  modalImageContainer: {
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 16,
  },
  modalImageWrapper: {
    width: 120,
    height: 120,
    borderRadius: 60,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 3,
    borderColor: '#10b981',
  },
  modalIrisImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  modalImageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingVertical: 4,
    alignItems: 'center',
  },
  modalImageCaption: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '500',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 24,
  },
  modalTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1f2937',
    marginLeft: 8,
  },
  modalCloseButton: {
    padding: 4,
  },
  modalDescription: {
    fontSize: 16,
    color: '#4b5563',
    lineHeight: 24,
    paddingHorizontal: 24,
  },
  dominantColorName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 4,
  },
  dominantColorConfidence: {
    fontSize: 14,
    color: '#6b7280',
  },
  colorCompositionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 16,
  },
  colorCompositionList: {
    gap: 12,
  },
  colorItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  colorSwatch: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  colorName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1f2937',
    flex: 1,
  },
  colorHex: {
    fontSize: 12,
    color: '#6b7280',
    fontFamily: 'monospace',
  },
  colorPercentage: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
    minWidth: 40,
    textAlign: 'right',
  },
  divider: {
    height: 1,
    marginVertical: 16,
  },
  colorCompositionSection: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  uniquePatternsSection: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  uniquePatternsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  uniquePatternsIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  uniquePatternsTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1f2937',
  },
});